apiVersion: v1
kind: Secret
metadata:
  name: {{ include "asr-batch-cronjob.fullname" . }}
  labels:
    {{- include "asr-batch-cronjob.labels" . | nindent 4 }}
type: Opaque
data:
  S3_BUCKET: {{ .Values.config.bucket | b64enc }}
  S3_PREFIX: {{ .Values.config.prefixIn | b64enc }}
  S3_PREFIX_LOG: {{ .Values.config.prefixLog | b64enc }}
  S3_PREFIX_OUT: {{ .Values.config.prefixOut | b64enc }}
  S3_KEY: {{ .Values.config.s3Key | b64enc }}
  S3_SECRET: {{ .Values.config.s3Secret | b64enc }}
  API_SECRET: {{ .Values.config.apiSecret | b64enc }}